repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 2f3fa1f
    hooks:
    -   id: black
